// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDh88Chibh81gqI2cKXHpbUbGuzfA3iK0',
    appId: '1:901455032664:web:79d2ee6fbf10662270f52d',
    messagingSenderId: '901455032664',
    projectId: 'fir-veggieverse',
    authDomain: 'fir-veggieverse.firebaseapp.com',
    storageBucket: 'fir-veggieverse.firebasestorage.app',
    measurementId: 'G-W59TGRTQLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuLH6wTCmc6KxmirhFC84bKkH3YePvMaA',
    appId: '1:901455032664:android:31a36d69c4c394e470f52d',
    messagingSenderId: '901455032664',
    projectId: 'fir-veggieverse',
    storageBucket: 'fir-veggieverse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD2bj3bP0WNoyW13a7e3lTk_k-3EP9clY',
    appId: '1:901455032664:ios:7ae72947bfd3e98370f52d',
    messagingSenderId: '901455032664',
    projectId: 'fir-veggieverse',
    storageBucket: 'fir-veggieverse.firebasestorage.app',
    iosBundleId: 'com.example.veggieverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD2bj3bP0WNoyW13a7e3lTk_k-3EP9clY',
    appId: '1:901455032664:ios:7ae72947bfd3e98370f52d',
    messagingSenderId: '901455032664',
    projectId: 'fir-veggieverse',
    storageBucket: 'fir-veggieverse.firebasestorage.app',
    iosBundleId: 'com.example.veggieverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDh88Chibh81gqI2cKXHpbUbGuzfA3iK0',
    appId: '1:901455032664:web:04b841ef8b69001570f52d',
    messagingSenderId: '901455032664',
    projectId: 'fir-veggieverse',
    authDomain: 'fir-veggieverse.firebaseapp.com',
    storageBucket: 'fir-veggieverse.firebasestorage.app',
    measurementId: 'G-YR1LZKK5XG',
  );
}
